env:
  - DOCKER_COMPOSE_VERSION=1.25.4

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - echo "MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE\nMONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME\nMONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD" > $TRAVIS_BUILD_DIR/database/database.env

script:
  - docker-compose up -d --build

after_script:
  - docker-compose down
