# Docker Engine release 18.06.0+
version: "3.7"

volumes:
  mongodata:

services:
  backend:
    container_name: backend-api
    build:
      context: ./backend
    image: drinkler/microservices-backend:latest
    ports:
      - ${HOST_PORT_BACKEND}:${CONTAINER_PORT_BACKEND}
    depends_on:
      - database
    restart: always

  database:
    container_name: database-mongo
    image: mongo:4.2.5
    env_file:
      - ./database/database.env
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - ${HOST_PORT_DATABASE}:${CONTAINER_PORT_DATABASE}

  frontend:
    container_name: frontend-angular
    build:
      context: ./frontend
    image: drinkler/microservices-frontend:latest
    depends_on:
      - backend
    ports:
      - ${HOST_PORT_FRONTEND}:${CONTAINER_PORT_FRONTEND}
    restart: always
