# Docker Engine release 18.06.0+
version: "3.7"

volumes:
  mongodata:

services:
  backend:
    container_name: backend-api
    build:
      context: ./backend
    image: drinkler/microservices-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: always

  database:
    container_name: database-mongo
    image: mongo:4.2.5
    restart: always
    environment:
      MONGO_INITDB_DATABASE: online-shop
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: LSuFDaaenPfdVMi4S
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

  frontend:
    container_name: frontend-angular
    build:
      context: ./frontend
    image: drinkler/microservices-frontend:latest
    depends_on:
      - backend
    ports:
      - "8081:80"
    restart: always
