apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out ./k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out ./k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - image: drinkler/microservices-backend:latest
          imagePullPolicy: ""
          name: backend-api
          ports:
            - containerPort: 8080
          env:
            - name: DB_CONNECTION
              value: "mongodb+srv://drinkler:Tf9OUDhSmQhnVxIh@onlineshop-dobyn.mongodb.net/test?retryWrites=true&w=majority"
            - name: PORT
              value: "8080"
            - name: JWT_KEY
              value: "5AE34D147B8ADA82FB2FAA85DEC52"
              # TODO: Set environmental variables
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
