apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out ./k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out ./k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          value: online-shop
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: LSuFDaaenPfdVMi4S
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        image: mongo:4.2.5
        imagePullPolicy: ""
        name: database-mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodata
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mongodata
        persistentVolumeClaim:
          claimName: mongodata
status: {}
